config/routes.rb
MyDepot::Application.routes.draw do
  get 'admin' => 'admin#index'

    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

  scope '(:locale)' do  #nest resources and roots in optional locale scope

    resources :users
    
    resources :orders

    resources :line_items

    resources :carts

    get "store/index"

    resources :products do
      get :who_bought, on: :member
    end
   

    root to: 'store#index', as: 'store'
   end 
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag "application" %><!-- <label id="code.slt"/> -->
  <%= javascript_include_tag "application" %><!-- <label id="code.jlt"/> -->
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> -->
</head>

<body class="<%= controller.controller_name %>">
  <!-- START:i18n -->
  <div id="banner">
<!-- START_HIGHLIGHT -->
    <%= form_tag store_path, class: 'locale' do %>
      <%= select_tag 'set_locale', 
        options_for_select(LANGUAGES, I18n.locale.to_s),
        onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
<!-- END_HIGHLIGHT -->
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
  </div>
<!-- END:i18n -->
  <div id="columns">
    <div id="side">
      <% if @cart %>
        <!-- START:hidden_div -->
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
        <!-- END:hidden_div -->
      <% end %>  
      
      <ul>
        <li><a href="http://www...."><%= t('.Home') %></a></li>
        <li><a href="http://www..../faq"><faq%= t('.Questions') %></a></li>
        <li><a href="http://www..../news"><%= t('.News') %></a></li>
        <li><a href="http://www..../contact"><%= t('.Contact') %></a></li>
      </ul>

      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders',   orders_path   %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete   %>
      <% end %>
    </div>
    <div id="main">
<!-- END_HIGHLIGHT -->
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
<!-- START_HIGHLIGHT -->
    </div>
  </div>
<!-- END_HIGHLIGHT -->
</body>
</html>